name: Build IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: List schemes
        run: xcodebuild -list -project ThreeOneOSFive.xcodeproj
      - name: Build IPA
        run: |
          SCHEME=$(xcodebuild -list -project ThreeOneOSFive.xcodeproj | awk '/Schemes:/{flag=1; next} flag && NF{print $1; exit}')
          echo "Usando scheme: $SCHEME"
          xcodebuild -project ThreeOneOSFive.xcodeproj -scheme "$SCHEME" -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" -derivedDataPath build
          mkdir Payload
          cp -R build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r ALEXITO-STORE.ipa Payload
      - uses: actions/upload-artifact@v4
        with:
          name: ALEXITO-STORE-IPA
          path: ALEXITO-STORE.ipa
