name: Build IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build IPA
        run: |
          xcodebuild -project ThreeOneOSFive.xcodeproj -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO -destination generic/platform=iOS build
          mkdir -p Payload
          APP=$(find. -name "*.app" | head -n 1)
          echo "APP $APP"
          cp -R "$APP" Payload/
          zip -r ThreeOneOSFive.ipa Payload
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: 3105-IPA
          path: ThreeOneOSFive.ipa
