name: Build IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build IPA
        run: |
          xcodebuild -project 3105/ThreeOneOSFive.xcodeproj -scheme ThreeOneOSFive -configuration Release -sdk iphoneos -archivePath build.xcarchive archive CODE_SIGNING_ALLOWED=NO
          mkdir -p Payload
          cp -R build.xcarchive/Products/Applications/ThreeOneOSFive.app Payload/
          zip -r 3105.ipa Payload
      - uses: actions/upload-artifact@v4
        with:
          name: 3105-IPA
          path: 3105.ipa
